class FunFactsList {
  static List<String> facts = [
    "Did you know that 'The Shawshank Redemption' was not a box office success but became a classic over time?",
    "The Beatles' 'Yesterday' is one of the most covered songs in history.",
    "The movie 'Jurassic Park' used groundbreaking special effects for its time, setting a new standard for CGI in films.",
    "The song 'Bohemian Rhapsody' by Queen was recorded in various sections, with the band members adding their parts individually.",
    "The first movie ever made is considered to be 'Roundhay Garden Scene,' filmed in Leeds in 1888.",
    "Elvis Presley's 'Jailhouse Rock' is often considered one of the first music videos due to its choreographed dance scenes.",
    "In 'The Matrix,' the code that appears on the screens is actually symbols from Japanese sushi recipes.",
    "The longest song ever recorded is 'The Rise and Fall of Bossanova.' It has a duration of 13 hours and 23 minutes.",
    "Meryl Streep holds the record for the most Oscar nominations, with 21 nominations over her career.",
    "The first feature film with synchronized dialogue was 'The Jazz Singer,' released in 1927.",
    "Michael Jackson's 'Thriller' music video is known for its iconic dance sequence and groundbreaking special effects.",
    "The highest-grossing film of all time (unadjusted for inflation) is 'Avengers: Endgame.'",
    "Bob Marley's 'No Woman, No Cry' was recorded live in London, and the audience's applause was later dubbed out.",
    "The 'Star Wars' franchise has one of the most recognizable soundtracks composed by John Williams.",
    "The first recorded instance of lip-syncing in a movie is in the 1927 film 'The Jazz Singer.'",
    "The movie 'Forrest Gump' used cutting-edge visual effects to insert Tom Hanks into historical footage.",
    "The famous 'I'm king of the world!' line from 'Titanic' was improvised by Leonardo DiCaprio.",
    "The longest-running Broadway musical is 'The Phantom of the Opera,' which debuted in 1988.",
    "The iconic '007' James Bond theme was composed by Monty Norman.",
    "The song 'Like a Rolling Stone' by Bob Dylan was recorded in a single take with the musicians improvising their parts.",
    "The first feature-length animated film is Disney's 'Snow White and the Seven Dwarfs,' released in 1937.",
    "The guitar solo in Pink Floyd's 'Comfortably Numb' is often considered one of the greatest guitar solos in rock history.",
    "The 'Harry Potter' film series is the highest-grossing film series based on a book.",
    "The first music video ever played on MTV was 'Video Killed the Radio Star' by The Buggles.",
    "The movie 'E.T. the Extra-Terrestrial' featured a puppet designed by Jim Henson, the creator of the Muppets.",
    "The term 'blockbuster' originated from the World War II practice of dropping bombs during air raids.",
    "The song 'Billie Jean' by Michael Jackson was the first music video by a black artist to air in heavy rotation on MTV.",
    "The 'Back to the Future' trilogy used groundbreaking visual effects to depict time travel and futuristic scenes.",
    "The song 'Sweet Child o' Mine' by Guns N' Roses was created during a rehearsal session when guitarist Slash was playing a riff.",
    "The first words spoken in a feature film are 'Wait a minute, wait a minute. You ain't heard nothin' yet!' in 'The Jazz Singer.'",
    "The 'Pirates of the Caribbean' film series is inspired by the Disneyland theme park ride of the same name.",
    "The Beatles' last public performance was on the rooftop of the Apple Corps building in London.",
    "The movie 'Inception' features a soundtrack that includes a slowed-down version of the song 'Non, Je Ne Regrette Rien' by Edith Piaf.",
    "The song 'I Will Always Love You' by Whitney Houston became one of the best-selling singles of all time.",
    "The movie 'The Godfather' is known for its iconic line: 'I'm gonna make him an offer he can't refuse.'",
    "The song 'Stairway to Heaven' by Led Zeppelin is often considered one of the greatest rock songs of all time.",
    "The first recorded instance of a Wilhelm scream, a stock sound effect, was in the film 'Distant Drums' (1951).",
    "The 'Toy Story' film series was the first entirely computer-animated feature film.",
    "The song 'Hallelujah' by Leonard Cohen has been covered by numerous artists and featured in various movies and TV shows.",
    "The movie 'Casablanca' has the famous line: 'Here's looking at you, kid.'",
    "The Rolling Stones' song 'Paint It, Black' was used in the opening credits of the TV show 'Tour of Duty.'",
    "The 'James Bond' film series is known for its suave and sophisticated fictional spy character.",
    "The song 'Superstition' by Stevie Wonder features the distinctive clavinet riff played by Wonder himself.",
    "The movie 'Gone with the Wind' is one of the highest-grossing films of all time when adjusted for inflation.",
    "The Beatles' rooftop concert was their last live performance as a group.",
    "The song 'Blitzkrieg Bop' by the Ramones is often considered one of the quintessential punk rock songs.",
    "The movie 'The Wizard of Oz' was one of the first films to use Technicolor for its vivid color scenes.",
    "The song 'Wish You Were Here' by Pink Floyd was written as a tribute to the band's former member Syd Barrett.",
    "Did you know that 'The Shawshank Redemption' was not a box office success but became a classic over time?",
    "The Beatles' 'Yesterday' is one of the most covered songs in history.",
    "The first movie ever made is considered to be 'Roundhay Garden Scene,' created in 1888.",
    "The 'Star Wars' film series was not originally expected to be a huge success.",
    "The sound of the velociraptors in 'Jurassic Park' is a combination of the sounds of tortoises mating and horses breathing.",
    "The longest song ever recorded is 'The Rise and Fall of Bossanova.' It's over 13 hours long!",
    "The first music video ever played on MTV was 'Video Killed the Radio Star' by The Buggles.",
    "The iconic 'Pink Floyd' album cover for 'The Dark Side of the Moon' was created by Storm Thorgerson and features no text or band name.",
    "The first recorded song in history is 'Hurrian Hymn No. 6.' It was written in cuneiform on a clay tablet in ancient Mesopotamia.",
    "The original name of the band 'Nirvana' was 'Skid Row.'",
    "The film 'Titanic' had a larger budget than the actual ship it depicted.",
    "The word 'hip-hop' was first used by rapper Keith Cowboy in 1978.",
    "The first movie ever made with synchronized sound is 'The Jazz Singer' (1927).",
    "The Beatles used the word 'love' 613 times in their songs.",
    "The longest-running Broadway show is 'The Phantom of the Opera.'",
    "The term 'rock and roll' was originally a euphemism for sex in rhythm and blues music.",
    "The first music video aired on MTV in 1981 was 'Video Killed the Radio Star' by The Buggles.",
    "The movie 'Pulp Fiction' does not have a traditional linear narrative structure.",
    "The world's longest-running radio show is the 'Grand Ole Opry' in Nashville, Tennessee.",
    "The first recorded instance of music piracy was in 1903 when sheet music was illegally duplicated.",
    "The 'Woo-hoo!' sound in 'Blur's' 'Song 2' was originally intended as a placeholder but was kept in the final version.",
    "The longest concert by a single artist lasted for over 27 hours and was performed by Irish singer-songwriter Damien Rice.",
    "The first music streaming service was called 'Napster' and was launched in 1999.",
    "The shortest song ever recorded is 'You Suffer' by Napalm Death, clocking in at just 1.316 seconds.",
    "The movie 'The Matrix' popularized the 'bullet time' special effect.",
    "The first music video ever made is often considered to be 'Bohemian Rhapsody' by Queen.",
    "The most expensive music video ever made is 'Scream' by Michael Jackson and Janet Jackson.",
    "The 'James Bond' film series is one of the longest-running and most successful franchises in cinema history.",
    "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
    "The world's first recorded computer-generated music was created by Alan Turing in 1951.",
    "The first feature-length animated film is 'Snow White and the Seven Dwarfs,' released by Disney in 1937.",
    "The longest-running TV show is 'The Simpsons,' which has been on the air since 1989.",
    "The first recorded song with an electric guitar is 'Adios Muchachos' by the Victor Dance Orchestra in 1927.",
    "The iconic 'Friends' TV show theme song, 'I'll Be There for You' by The Rembrandts, was written in just two days.",
    "The highest-grossing movie of all time (adjusted for inflation) is 'Gone with the Wind.'",
    "The first music CD commercially released was 'The Visitors' by ABBA in 1982.",
    "The movie 'Forrest Gump' was based on a novel of the same name by Winston Groom.",
    "The longest-running film franchise is 'Godzilla,' which has been in production since 1954.",
    "The first known recording of music was made by Édouard-Léon Scott de Martinville in 1860, predating Thomas Edison's phonograph.",
    "The first animated feature film is often considered to be 'Snow White and the Seven Dwarfs,' released by Disney in 1937.",
    "The world's oldest surviving musical instruments are bone flutes dating back to around 40,000 years ago.",
    "The first known music notation system is from ancient Greece, dating back to around 450 BCE.",
    "The largest film industry by the number of feature films produced annually is Bollywood in India.",
    "The first recorded instance of lip-syncing is attributed to the Italian castrato Alessandro Moreschi in the early 20th century.",
    "The first movie with a CGI character in a leading role is 'Toy Story' (1995).",
  ];
}
